version: '2'
networks:
  exmpirenet:
    driver: bridge
services:
  storefront:
    image: ${CONTAINER_IMAGE}
    networks:
    - exmpirenet
    expose:
    - "${STOREFRONT_PORT}"    
    external_links:
    - exmpire_ajax_1:ajax
    environment:
    - PROJECT=${PROJECT}
    - SERVICE=${CONTAINER}
    volumes:
    - ${BASE_DIR}/emmpire_storefront:/usr/local/lib/emmpire_storefront
    - ${BASE_DIR}/emmpire_storefront/compose/runapp.sh:/usr/local/bin/runapp.sh
    working_dir: /usr/local/lib/emmpire_storefront
