version: '2'
networks:
  emmpairnet:
    driver: bridge
services:
  storefront:
    image: ${CONTAINER_IMAGE}
    networks:
    - emmpairnet
    expose:
    - "${STOREFRONT_PORT}"    
    environment:
    - PROJECT=${PROJECT}
    - SERVICE=${CONTAINER}
    volumes:
    - ${BASE_DIR}/emmpair_storefront:/usr/local/lib/emmpair_storefront
    - ${BASE_DIR}/emmpair_storefront/compose/runapp.sh:/usr/local/bin/runapp.sh
    working_dir: /usr/local/lib/emmpair_storefront
