version: '2'
networks:
  properlynet:
    driver: bridge
services:
  storefront:
    image: ${CONTAINER_IMAGE}
    networks:
    - properlynet
    expose:
    - "${STOREFRONT_PORT}"
    environment:
    - PROJECT=${PROJECT}
    - SERVICE=${CONTAINER}
    # ...
    - APP_CNM_CONTRACT_ADDRESS=${CNM_CONTRACT_ADDRESS}
    volumes:
    - ${BASE_DIR}/properly_storefront:/usr/local/lib/properly_storefront
    - ${BASE_DIR}/properly_storefront/compose/runapp.sh:/usr/local/bin/runapp.sh
    working_dir: /usr/local/lib/properly_storefront
